version: 2

models:
    - name: dim_games
      description: "Games (dimension)"
      columns:
          - name: game_id
            description: "The game id, PK"
            tests:
                - unique
                - not_null

    - name: exchange_rates
      description: "Exchange rates"

    - name: stg_transactions
      description: "Raw transactions"
      columns:
          - name: transaction_id
            description: "The transaction id, PK"
            tests:
                - unique
                - not_null